
INSERT INTO T_TIPO_CLASSIFICACAO (id, CLASSIFICACAO) VALUES (1, 'LEVE');
INSERT INTO T_TIPO_CLASSIFICACAO (id, CLASSIFICACAO) VALUES (2, 'MEDIA');
INSERT INTO T_TIPO_CLASSIFICACAO (id, CLASSIFICACAO) VALUES (3, 'GRAVE');

